### ISSUE TITLE
不错。。。

### ISSUE THREAD

**Issue by hacker-mao** [DHWxiao/EvaluationTools#1]

**Comment by hacker-mao** [comment]
0

**Comment by DHWxiao** [comment]
放在github 上的版本太老了，已经不适用了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: D4rk3r ***@***.***&gt;
发送时间: 2021年11月8日 19:16
收件人: DHWxiao/EvaluationTools ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[DHWxiao/EvaluationTools] 不错。。。 (Issue #1)





 
Closed #1.
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hacker-mao** [comment]
> 放在github 上的版本太老了，已经不适用了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: D4rk3r ***@***.***&gt; 发送时间: 2021年11月8日 19:16 收件人: DHWxiao/EvaluationTools ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[DHWxiao/EvaluationTools] 不错。。。 (Issue #1) Closed #1. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

目前不更新了吗

**Comment by DHWxiao** [comment]
在更新的，只是没有对外公开，你有兴趣的话可以加我微信：xhuSoul




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DHWxiao/EvaluationTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月8日(星期一) 晚上7:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DHWxiao/EvaluationTools] 不错。。。 (Issue #1)





  
放在github 上的版本太老了，已经不适用了 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: D4rk3r @.&gt; 发送时间: 2021年11月8日 19:16 收件人: DHWxiao/EvaluationTools @.&gt; 抄送: Subscribed @.***&gt; 主题: 回复：[DHWxiao/EvaluationTools] 不错。。。 (Issue #1) Closed #1. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
目前不更新了吗
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
